server:
  port: 8080
  address: 0.0.0.0

dashscope:
  api:
    key: sk-49847dd4810540b0936f51c43e7ea4de
  model:
    name: qwen-plus
  prompt:
    template: 请联网搜索,为游戏{gameName}生成一段简短的游戏介绍,不超过150字.如果发现这个游戏名字是乱填的不存在,就返回无介绍,不要瞎编。但是有新闻报道的即将发售的游戏可以写上新闻、测试资讯、预计发售日期等

spring:
  application:
    name: game
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m
  datasource:
    url: jdbc:sqlite:game.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
    hikari:
      # SQLite-specific connection pool settings
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false