name: Build Native Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-native-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 with GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.9.9

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build native image
        run: |
          mkdir -p target
          native-image \
            --no-fallback \
            --enable-http \
            --enable-https \
            --initialize-at-build-time \
            -H:Name=game-1.0 \
            -H:Class=org.springframework.boot.loader.PropertiesLauncher \
            -jar target/game-1.0.jar

      - name: Upload native executable
        uses: actions/upload-artifact@v4
        with:
          name: native-app
          path: game-1.0
